# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testdockvenu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockervenu.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_86ab400b1c5e44c3a8cbdb784da6d91c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f5e2a40d17a04afd829f3018a3aec3a8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockervenu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_86ab400b1c5e44c3a8cbdb784da6d91c }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdockvenu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_72f146e1017f450cb3d8259ab776be40 }}
        images: 'testdockervenu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_86ab400b1c5e44c3a8cbdb784da6d91c }}/studentperformance:${{ github.sha }}'